### ISSUE TITLE
fixing Like button

### ISSUE THREAD

**Issue by tinkten7** [p-sai-gowtham/socialmediaAPP#1]
I can add functioning to the Like button for your app

**Comment by p-sai-gowtham** [comment]
ok then you can go through the fixing

**Comment by tinkten7** [comment]
assign me the label for hacktoberfest

**Comment by p-sai-gowtham** [comment]
you can start now

**Comment by tinkten7** [comment]
alright

**Comment by tinkten7** [comment]
issue has been resolved

**Comment by p-sai-gowtham** [comment]
thanks for your valuable contribution
